MovieShop/MovieShopMVC/Models/ErrorViewModel.cs
namespace MovieShopMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShop/MovieShopMVC/Controllers/HomeController.cs
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Models;
using System.Diagnostics;
using ApplicationCore.Contracts.Services;

namespace MovieShopMVC.Controllers
{
    public class HomeController : Controller
    {

        private readonly IMovieService _movieService;

        public HomeController(IMovieService movieService)
        {
            //_movieService = new MovieService(); not the good way - concreate instantiate
            // instead we prefer 
            _movieService = movieService;


        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {

            //our controllers are very thin/lean
            //most of your logic should come from other dependencies, services
            //we create
            //

            //var movieService = new MovieService();

            //model data
            var movies= await _movieService.GetTop30GrossingMovies();

            return View(movies);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        public IActionResult TopMovies()
        {
            return View("Privacy");//overload - you could specify which cshtml to direct to via parameters.
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShop/MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers 
{
    public class MoviesController : Controller
    { 



        private IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task<IActionResult> Details(int id)
        {
            // Movie Service with Details  
            // pass the movie details data to view
            var moviedetails = await _movieService.GetMovieDatails(id);
            return View(moviedetails);
        }


        public async Task<IActionResult> Genres(int id, int pageSize=30, int pageNumber=1)
        {
            var pagedMovies = await _movieService.GetMoviesByGenrePagination(id, pageSize, pageNumber);
            return View("PagedMovies",pagedMovies); 
        }
    }
}

MovieShop/MovieShopMVC/Views/Home/Index.cshtml
@model List<ApplicationCore.Models.MovieCardModel>


@{
    ViewData["Title"] = "Home Page";
}

<div class = "rounded">
    <div class="container-fluid">
        <div class="row">
            @foreach(var movie in Model)
            {
                <div class=" col-6 col-xl-12 col-sm-4 col-lg-3 ">
                    <partial name="_MovieCard" model="movie" />

                </div>

            }
        </div>
    </div>
</div>



<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MovieShop/MovieShopMVC/Views/Home/TopMovies.cshtml
<h1>movies</h1>

MovieShop/MovieShopMVC/Views/Movies/Details.cshtml
@Model ApplicationCore.Models.MovieDetailsModel
<h2>Movie Details</h2>
<h3>@Model.Title</h3>
<h6>
    @Model.Overview
</h6>

MovieShop/MovieShopMVC/Views/Movies/PagedMovies.cshtml
@Model ApplicationCore.Models.PagedResultSet<ApplicationCore.Models.MovieCardModel>
    @foreach (var movie in Model.Data)
    {
        <partial name="_MovieCard" model="movie"/>
    }

<nav aria-label="Page Navigation example">
    <ul class="pagination">

        @for(var i =0; i< Model.TotalPages; i++)
            {
                <li class=" ="page-item">
                    <a class="page-link" href="#">
                        @i
                    </a>
                </li>
            }
    </ul>

</nav>

MovieShop/MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieShopMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShop/MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardModel

<div class="card mb-4">
    <a asp-action="Details" asp-controller="Movies" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" alt="@Model.Title" class="img-fluid" />
    </a>

</div>